version: "3"

services:
  app:
    build:
      context: .
      dockerfile: ./.docker/python/Dockerfile
    container_name: fast-room-app
    volumes:
      - type: bind
        source: .
        target: /src
      - .docker/.dockervenv:/src/.venv
    ports:
      - 8000:8000 # ホストマシンのポート8000を、docker内のポート8000に接続する
    depends_on:
      - db
  # db:
  #   image: postgres:14
  #   container_name: fastapi-postgres
  #   ports:
  #     - 5432:5432
  #   volumes:
  #     - db-store:/var/lib/postgresql/data
  #   environment:
  #     POSTGRES_USER: "user"
  #     POSTGRES_PASSWORD: "password"
  #     POSTGRES_DB: "postgres_db"

  db:
    build:
      context: .
      dockerfile: ./.docker/mysql/Dockerfile
    container_name: fast-room-db
    environment:
      MYSQL_DATABASE: "room_db" # 初期データベースとしてdemoを設定
      MYSQL_ROOT_PASSWORD: "passwd"
      MYSQL_ROOT_HOST: "%"
      MYSQL_USER: "user"
      MYSQL_PASSWORD: "passwd"
    volumes:
      - mysql_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password # MySQL8.0ではデフォルトが"caching_sha2_password"で、ドライバが非対応のため変更
    ports:
      - 33306:3306 # ホストマシンのポート33306を、docker内のポート3306に接続する
volumes:
  mysql_data:
